// verify_determinism.c — determinism verification harness for the PufferLib
// NetHack env. Standalone binary; does not link PufferLib.
//
// Build (one-liner, run from PufferLib repo root):
//
//   clang -O2 -Wall -Wextra -std=gnu11 \
//       -I./vendor/nle/include -I./ocean/nethack \
//       -DNETHACK_USE_BLSTATS=1 \
//       ocean/nethack/verify_determinism.c \
//       -o verify_determinism -ldl -lpthread -lm
//
// Usage:
//   ./verify_determinism record --seed 42 --steps 1000 --action-seed 99 --out /tmp/g1.bin
//   ./verify_determinism replay --in /tmp/g1.bin [--bytewise]
//
// Strategy:
//   1. We include ocean/nethack/nethack.h to reuse init / c_step / c_close
//      and all of the helper machinery (dlopen-into-memfd, vardir, obs pack,
//      drain prompts, etc.).
//   2. We provide our OWN c_reset variant (c_reset_seeded) that passes a
//      fixed nle_seeds_init_t* to fn_start instead of NULL. We do this by
//      copy-pasting the body of c_reset from nethack.h and threading a seed
//      argument through. We deliberately do NOT modify nethack.h so the
//      production env code stays untouched.
//   3. The action stream is generated by a tiny deterministic PRNG seeded
//      with --action-seed; we DO NOT use the libc rand()/srand() pair so the
//      action stream is portable and reproducible across runs.
//   4. We hash per-step observations using an embedded public-domain SHA1.
//
// See the comment block at the very bottom of this file for sanity-test
// results and any non-determinism findings.

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <inttypes.h>
#include <errno.h>
#include <link.h>
#include <elf.h>

// ---------------------------------------------------------------------------
// Silence warnings in nethack.h / profile.h that are not relevant to this
// test harness (unused static helpers, unused parameters in the profiler
// macros once we don't define NETHACK_PROFILE, etc.). We re-enable warnings
// after the include so our own code is still strictly checked.
// ---------------------------------------------------------------------------
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-parameter"
#pragma clang diagnostic ignored "-Wunused-variable"
#pragma clang diagnostic ignored "-Wunused-function"
#include "nethack.h"
#pragma clang diagnostic pop

// ---------------------------------------------------------------------------
// Tiny SHA1 (public domain, derived from Steve Reid's reference impl).
// ---------------------------------------------------------------------------
typedef struct {
    uint32_t state[5];
    uint32_t count[2];
    uint8_t  buffer[64];
} SHA1_CTX;

#define SHA1_ROL(value, bits) (((value) << (bits)) | ((value) >> (32 - (bits))))
#define SHA1_BLK0(i) (block->l[i] = __builtin_bswap32(block->l[i]))
#define SHA1_BLK(i) (block->l[i&15] = SHA1_ROL(block->l[(i+13)&15]^block->l[(i+8)&15] \
    ^block->l[(i+2)&15]^block->l[i&15],1))
#define SHA1_R0(v,w,x,y,z,i) z+=((w&(x^y))^y)+SHA1_BLK0(i)+0x5A827999+SHA1_ROL(v,5);w=SHA1_ROL(w,30);
#define SHA1_R1(v,w,x,y,z,i) z+=((w&(x^y))^y)+SHA1_BLK(i)+0x5A827999+SHA1_ROL(v,5);w=SHA1_ROL(w,30);
#define SHA1_R2(v,w,x,y,z,i) z+=(w^x^y)+SHA1_BLK(i)+0x6ED9EBA1+SHA1_ROL(v,5);w=SHA1_ROL(w,30);
#define SHA1_R3(v,w,x,y,z,i) z+=(((w|x)&y)|(w&x))+SHA1_BLK(i)+0x8F1BBCDC+SHA1_ROL(v,5);w=SHA1_ROL(w,30);
#define SHA1_R4(v,w,x,y,z,i) z+=(w^x^y)+SHA1_BLK(i)+0xCA62C1D6+SHA1_ROL(v,5);w=SHA1_ROL(w,30);

static void sha1_transform(uint32_t state[5], const uint8_t buffer[64]) {
    uint32_t a, b, c, d, e;
    typedef union { uint8_t c[64]; uint32_t l[16]; } CHAR64LONG16;
    CHAR64LONG16 blk;
    CHAR64LONG16* block = &blk;
    memcpy(block, buffer, 64);
    a = state[0]; b = state[1]; c = state[2]; d = state[3]; e = state[4];
    SHA1_R0(a,b,c,d,e, 0); SHA1_R0(e,a,b,c,d, 1); SHA1_R0(d,e,a,b,c, 2); SHA1_R0(c,d,e,a,b, 3);
    SHA1_R0(b,c,d,e,a, 4); SHA1_R0(a,b,c,d,e, 5); SHA1_R0(e,a,b,c,d, 6); SHA1_R0(d,e,a,b,c, 7);
    SHA1_R0(c,d,e,a,b, 8); SHA1_R0(b,c,d,e,a, 9); SHA1_R0(a,b,c,d,e,10); SHA1_R0(e,a,b,c,d,11);
    SHA1_R0(d,e,a,b,c,12); SHA1_R0(c,d,e,a,b,13); SHA1_R0(b,c,d,e,a,14); SHA1_R0(a,b,c,d,e,15);
    SHA1_R1(e,a,b,c,d,16); SHA1_R1(d,e,a,b,c,17); SHA1_R1(c,d,e,a,b,18); SHA1_R1(b,c,d,e,a,19);
    SHA1_R2(a,b,c,d,e,20); SHA1_R2(e,a,b,c,d,21); SHA1_R2(d,e,a,b,c,22); SHA1_R2(c,d,e,a,b,23);
    SHA1_R2(b,c,d,e,a,24); SHA1_R2(a,b,c,d,e,25); SHA1_R2(e,a,b,c,d,26); SHA1_R2(d,e,a,b,c,27);
    SHA1_R2(c,d,e,a,b,28); SHA1_R2(b,c,d,e,a,29); SHA1_R2(a,b,c,d,e,30); SHA1_R2(e,a,b,c,d,31);
    SHA1_R2(d,e,a,b,c,32); SHA1_R2(c,d,e,a,b,33); SHA1_R2(b,c,d,e,a,34); SHA1_R2(a,b,c,d,e,35);
    SHA1_R2(e,a,b,c,d,36); SHA1_R2(d,e,a,b,c,37); SHA1_R2(c,d,e,a,b,38); SHA1_R2(b,c,d,e,a,39);
    SHA1_R3(a,b,c,d,e,40); SHA1_R3(e,a,b,c,d,41); SHA1_R3(d,e,a,b,c,42); SHA1_R3(c,d,e,a,b,43);
    SHA1_R3(b,c,d,e,a,44); SHA1_R3(a,b,c,d,e,45); SHA1_R3(e,a,b,c,d,46); SHA1_R3(d,e,a,b,c,47);
    SHA1_R3(c,d,e,a,b,48); SHA1_R3(b,c,d,e,a,49); SHA1_R3(a,b,c,d,e,50); SHA1_R3(e,a,b,c,d,51);
    SHA1_R3(d,e,a,b,c,52); SHA1_R3(c,d,e,a,b,53); SHA1_R3(b,c,d,e,a,54); SHA1_R3(a,b,c,d,e,55);
    SHA1_R3(e,a,b,c,d,56); SHA1_R3(d,e,a,b,c,57); SHA1_R3(c,d,e,a,b,58); SHA1_R3(b,c,d,e,a,59);
    SHA1_R4(a,b,c,d,e,60); SHA1_R4(e,a,b,c,d,61); SHA1_R4(d,e,a,b,c,62); SHA1_R4(c,d,e,a,b,63);
    SHA1_R4(b,c,d,e,a,64); SHA1_R4(a,b,c,d,e,65); SHA1_R4(e,a,b,c,d,66); SHA1_R4(d,e,a,b,c,67);
    SHA1_R4(c,d,e,a,b,68); SHA1_R4(b,c,d,e,a,69); SHA1_R4(a,b,c,d,e,70); SHA1_R4(e,a,b,c,d,71);
    SHA1_R4(d,e,a,b,c,72); SHA1_R4(c,d,e,a,b,73); SHA1_R4(b,c,d,e,a,74); SHA1_R4(a,b,c,d,e,75);
    SHA1_R4(e,a,b,c,d,76); SHA1_R4(d,e,a,b,c,77); SHA1_R4(c,d,e,a,b,78); SHA1_R4(b,c,d,e,a,79);
    state[0] += a; state[1] += b; state[2] += c; state[3] += d; state[4] += e;
}

static void sha1_init(SHA1_CTX* ctx) {
    ctx->state[0] = 0x67452301; ctx->state[1] = 0xEFCDAB89;
    ctx->state[2] = 0x98BADCFE; ctx->state[3] = 0x10325476;
    ctx->state[4] = 0xC3D2E1F0;
    ctx->count[0] = ctx->count[1] = 0;
}

static void sha1_update(SHA1_CTX* ctx, const void* data, size_t len) {
    const uint8_t* p = (const uint8_t*)data;
    uint32_t i, j;
    j = ctx->count[0];
    if ((ctx->count[0] += (uint32_t)(len << 3)) < j) ctx->count[1]++;
    ctx->count[1] += (uint32_t)(len >> 29);
    j = (j >> 3) & 63;
    if ((j + len) > 63) {
        memcpy(&ctx->buffer[j], p, (i = 64 - j));
        sha1_transform(ctx->state, ctx->buffer);
        for (; i + 63 < len; i += 64) sha1_transform(ctx->state, &p[i]);
        j = 0;
    } else { i = 0; }
    memcpy(&ctx->buffer[j], &p[i], len - i);
}

static void sha1_final(SHA1_CTX* ctx, uint8_t digest[20]) {
    uint8_t finalcount[8];
    for (int i = 0; i < 8; i++)
        finalcount[i] = (uint8_t)((ctx->count[(i >= 4 ? 0 : 1)] >> ((3 - (i & 3)) * 8)) & 255);
    uint8_t c = 0x80;
    sha1_update(ctx, &c, 1);
    while ((ctx->count[0] & 504) != 448) {
        c = 0x00;
        sha1_update(ctx, &c, 1);
    }
    sha1_update(ctx, finalcount, 8);
    for (int i = 0; i < 20; i++)
        digest[i] = (uint8_t)((ctx->state[i >> 2] >> ((3 - (i & 3)) * 8)) & 255);
}

// ---------------------------------------------------------------------------
// Deterministic action PRNG — SplitMix64. We do not use rand()/srand() so
// the action stream is reproducible across libc versions / platforms.
// ---------------------------------------------------------------------------
static uint64_t splitmix64(uint64_t* s) {
    uint64_t z = (*s += 0x9E3779B97F4A7C15ULL);
    z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9ULL;
    z = (z ^ (z >> 27)) * 0x94D049BB133111EBULL;
    return z ^ (z >> 31);
}

// ---------------------------------------------------------------------------
// c_reset_seeded: same as c_reset (nethack.h) but passes a fixed
// nle_seeds_init_t* to fn_start. Copy-pasted body to avoid touching
// nethack.h. Note: we still call init() first to set up the env.
// ---------------------------------------------------------------------------
static void c_reset_seeded(Nethack* env, unsigned long core_seed, unsigned long disp_seed) {
    if (env->ctx != NULL && env->fn_end) {
        env->fn_end(env->ctx);
        env->ctx = NULL;
    }
    if (env->dl_handle != NULL) {
        nethack_unload_lib(env);
    }

    if (nethack_load_lib(env) != 0) {
        fprintf(stderr, "verify_determinism: failed to load libnethack\n");
        exit(2);
    }
    nethack_bind_obs(env);
    env->obs.action = 0;
    env->obs.done = 0;
    env->obs.in_normal_game = 0;
    env->obs.how_done = 0;

    if (env->fn_start == NULL) {
        fprintf(stderr, "verify_determinism: fn_start is NULL\n");
        exit(2);
    }

    nle_seeds_init_t seeds;
    memset(&seeds, 0, sizeof(seeds));
    seeds.seeds[0] = core_seed;
    seeds.seeds[1] = disp_seed;
    seeds.reseed = 0;  // anti-TAS reseed disabled => deterministic

    env->ctx = env->fn_start(&env->obs, NULL, &seeds, &env->settings);

    nethack_drain_prompts_cat(env, PROF_FN_STEPS_RESET_DRAIN);

    env->tick = 0;
    env->prev_score = 0;
#if NETHACK_USE_BLSTATS
    env->prev_depth = (int)env->blstats[NLE_BL_DEPTH];
#else
    env->prev_depth = 1;
#endif
    env->episode_return = 0.0f;
    env->episode_length = 0;
    env->episode_start_time = nethack_current_time(env);
    env->episode_valid_moves = 0;
    env->episode_illegal_actions = 0;
    env->episode_new_tiles = 0;
    memset(env->visited, 0, sizeof(env->visited));
    env->visited_level = 0;
    env->rewards[0] = 0.0f;
    env->terminals[0] = 0.0f;
    nethack_pack_obs(env);
}

// ---------------------------------------------------------------------------
// Golden file format
// ---------------------------------------------------------------------------
#define GOLDEN_MAGIC   0x4E484447u  // 'NHDG' (NetHack Determinism Golden)
#define GOLDEN_VERSION 1u

typedef struct __attribute__((packed)) {
    uint32_t magic;
    uint32_t version;
    uint64_t seed;
    uint64_t action_seed;
    uint64_t n_steps;
    uint64_t obs_size;
    uint32_t num_actions;
    uint32_t use_blstats;     // for sanity
} GoldenHeader;

typedef struct __attribute__((packed)) {
    int32_t action;
    uint8_t hash[20];
    float   reward;
    uint8_t terminal;
    uint8_t _pad[3];
} GoldenRecord;

// ---------------------------------------------------------------------------
// Env construction helpers (PufferLib-free)
// ---------------------------------------------------------------------------
static Nethack* make_env(void) {
    Nethack* env = calloc(1, sizeof(Nethack));
    if (!env) { perror("calloc"); exit(2); }
    // Allocate the agent-facing buffers. PufferLib normally owns these.
    env->num_agents = 1;
    env->observations = calloc(NETHACK_OBS_SIZE, 1);
    env->actions      = calloc(1, sizeof(float));
    env->rewards      = calloc(1, sizeof(float));
    env->terminals    = calloc(1, sizeof(float));
    if (!env->observations || !env->actions || !env->rewards || !env->terminals) {
        fprintf(stderr, "make_env: alloc failed\n"); exit(2);
    }
    init(env);
    return env;
}

static void free_env(Nethack* env) {
    c_close(env);
    free(env->observations);
    free(env->actions);
    free(env->rewards);
    free(env->terminals);
    free(env);
}

// ---------------------------------------------------------------------------
// Hash a single step's observation+reward+terminal
// ---------------------------------------------------------------------------
static void hash_step(const Nethack* env, uint8_t out[20]) {
    SHA1_CTX c; sha1_init(&c);
    sha1_update(&c, env->observations, NETHACK_OBS_SIZE);
    sha1_update(&c, &env->rewards[0], sizeof(float));
    sha1_update(&c, &env->terminals[0], sizeof(float));
    sha1_final(&c, out);
}

static void hex20(const uint8_t h[20], char out[41]) {
    static const char* hx = "0123456789abcdef";
    for (int i = 0; i < 20; i++) {
        out[2*i]   = hx[(h[i] >> 4) & 0xf];
        out[2*i+1] = hx[h[i] & 0xf];
    }
    out[40] = '\0';
}

// ---------------------------------------------------------------------------
// dl_iterate_phdr callback to dump writable LOAD segments of libnethack.so
// ---------------------------------------------------------------------------
typedef struct {
    SHA1_CTX sha;
    uint64_t total_bytes;
    int found;
} BytewiseCtx;

static int bytewise_cb(struct dl_phdr_info* info, size_t size, void* data) {
    (void)size;
    BytewiseCtx* ctx = (BytewiseCtx*)data;
    const char* name = info->dlpi_name ? info->dlpi_name : "";
    // Match libnethack.so (loaded via memfd path /proc/self/fd/N).
    if (!strstr(name, "libnethack") && !strstr(name, "memfd") &&
        !strstr(name, "/proc/self/fd/")) {
        return 0;
    }
    ctx->found = 1;
    for (int i = 0; i < info->dlpi_phnum; i++) {
        const ElfW(Phdr)* ph = &info->dlpi_phdr[i];
        if (ph->p_type != PT_LOAD) continue;
        if (!(ph->p_flags & PF_W)) continue;  // writable only
        const void* base = (const void*)(info->dlpi_addr + ph->p_vaddr);
        size_t len = ph->p_memsz;
        sha1_update(&ctx->sha, base, len);
        ctx->total_bytes += len;
    }
    return 0;
}

static void bytewise_dump(void) {
    BytewiseCtx ctx;
    memset(&ctx, 0, sizeof(ctx));
    sha1_init(&ctx.sha);
    dl_iterate_phdr(bytewise_cb, &ctx);
    uint8_t digest[20];
    sha1_final(&ctx.sha, digest);
    char hex[41]; hex20(digest, hex);
    if (!ctx.found) {
        fprintf(stderr, "bytewise: WARNING — could not find libnethack.so via dl_iterate_phdr\n");
    }
    printf("bytewise: writable_bytes=%" PRIu64 " sha1=%s\n", ctx.total_bytes, hex);
}

// ---------------------------------------------------------------------------
// CLI parsing
// ---------------------------------------------------------------------------
typedef struct {
    const char* mode;   // "record" or "replay"
    uint64_t    seed;
    uint64_t    steps;
    uint64_t    action_seed;
    const char* out_path;
    const char* in_path;
    int         bytewise;
} Args;

static void usage(const char* prog) {
    fprintf(stderr,
        "Usage:\n"
        "  %s record --seed S --steps N --action-seed A --out FILE\n"
        "  %s replay --in FILE [--bytewise]\n", prog, prog);
}

static int parse_args(int argc, char** argv, Args* a) {
    memset(a, 0, sizeof(*a));
    if (argc < 2) return -1;
    a->mode = argv[1];
    for (int i = 2; i < argc; i++) {
        const char* k = argv[i];
        const char* v = (i + 1 < argc) ? argv[i+1] : NULL;
        if      (!strcmp(k, "--seed"))        { if (!v) return -1; a->seed = strtoull(v,0,0); i++; }
        else if (!strcmp(k, "--steps"))       { if (!v) return -1; a->steps = strtoull(v,0,0); i++; }
        else if (!strcmp(k, "--action-seed")) { if (!v) return -1; a->action_seed = strtoull(v,0,0); i++; }
        else if (!strcmp(k, "--out"))         { if (!v) return -1; a->out_path = v; i++; }
        else if (!strcmp(k, "--in"))          { if (!v) return -1; a->in_path = v; i++; }
        else if (!strcmp(k, "--bytewise"))    { a->bytewise = 1; }
        else { fprintf(stderr, "unknown arg: %s\n", k); return -1; }
    }
    return 0;
}

// ---------------------------------------------------------------------------
// Record mode
// ---------------------------------------------------------------------------
static int do_record(const Args* a) {
    if (!a->out_path || a->steps == 0) { usage("verify_determinism"); return 1; }

    Nethack* env = make_env();
    c_reset_seeded(env, (unsigned long)a->seed, (unsigned long)a->seed);

    FILE* f = fopen(a->out_path, "wb");
    if (!f) { perror("fopen out"); free_env(env); return 1; }

    GoldenHeader h = {
        .magic = GOLDEN_MAGIC,
        .version = GOLDEN_VERSION,
        .seed = a->seed,
        .action_seed = a->action_seed,
        .n_steps = a->steps,
        .obs_size = NETHACK_OBS_SIZE,
        .num_actions = NETHACK_NUM_ACTIONS,
        .use_blstats = NETHACK_USE_BLSTATS,
    };
    if (fwrite(&h, sizeof(h), 1, f) != 1) { perror("fwrite header"); fclose(f); free_env(env); return 1; }

    uint64_t prng = a->action_seed + 0x12345ULL;  // non-zero offset
    for (uint64_t step = 0; step < a->steps; step++) {
        uint64_t r = splitmix64(&prng);
        int32_t action = (int32_t)(r % (uint64_t)NETHACK_NUM_ACTIONS);
        env->actions[0] = (float)action;
        c_step(env);

        GoldenRecord rec;
        memset(&rec, 0, sizeof(rec));
        rec.action = action;
        hash_step(env, rec.hash);
        rec.reward = env->rewards[0];
        rec.terminal = (env->terminals[0] != 0.0f) ? 1 : 0;
        if (fwrite(&rec, sizeof(rec), 1, f) != 1) {
            perror("fwrite record"); fclose(f); free_env(env); return 1;
        }
    }

    fclose(f);
    printf("record: wrote %" PRIu64 " steps to %s (obs_size=%d)\n",
           a->steps, a->out_path, NETHACK_OBS_SIZE);
    free_env(env);
    return 0;
}

// ---------------------------------------------------------------------------
// Replay mode
// ---------------------------------------------------------------------------
static void dump_chars(const Nethack* env) {
#if NETHACK_USE_CHARS
    fprintf(stderr, "--- chars grid (21x79) ---\n");
    for (int r = 0; r < NH_ROWS; r++) {
        for (int c = 0; c < NH_COLS; c++) {
            unsigned char ch = env->chars[r * NH_COLS + c];
            fputc(ch ? ch : ' ', stderr);
        }
        fputc('\n', stderr);
    }
#else
    (void)env;
    fprintf(stderr, "(chars obs disabled)\n");
#endif
    fprintf(stderr, "--- first 32 obs bytes ---\n");
    for (int i = 0; i < 32 && i < NETHACK_OBS_SIZE; i++) {
        fprintf(stderr, "%02x", env->observations[i]);
    }
    fprintf(stderr, "\n");
}

static int do_replay(const Args* a) {
    if (!a->in_path) { usage("verify_determinism"); return 1; }
    FILE* f = fopen(a->in_path, "rb");
    if (!f) { perror("fopen in"); return 1; }

    GoldenHeader h;
    if (fread(&h, sizeof(h), 1, f) != 1) { perror("fread header"); fclose(f); return 1; }
    if (h.magic != GOLDEN_MAGIC) {
        fprintf(stderr, "replay: bad magic 0x%08x (expected 0x%08x)\n", h.magic, GOLDEN_MAGIC);
        fclose(f); return 1;
    }
    if (h.version != GOLDEN_VERSION) {
        fprintf(stderr, "replay: version mismatch %u vs %u\n", h.version, GOLDEN_VERSION);
        fclose(f); return 1;
    }
    if (h.obs_size != (uint64_t)NETHACK_OBS_SIZE) {
        fprintf(stderr, "replay: obs_size mismatch %" PRIu64 " vs %d (recompile with same NETHACK_USE_* flags)\n",
                h.obs_size, NETHACK_OBS_SIZE);
        fclose(f); return 1;
    }
    if (h.num_actions != (uint32_t)NETHACK_NUM_ACTIONS) {
        fprintf(stderr, "replay: num_actions mismatch %u vs %d\n",
                h.num_actions, NETHACK_NUM_ACTIONS);
        fclose(f); return 1;
    }
    printf("replay: header seed=%" PRIu64 " action_seed=%" PRIu64 " n_steps=%" PRIu64 " obs_size=%" PRIu64 "\n",
           h.seed, h.action_seed, h.n_steps, h.obs_size);

    Nethack* env = make_env();
    c_reset_seeded(env, (unsigned long)h.seed, (unsigned long)h.seed);

    for (uint64_t step = 0; step < h.n_steps; step++) {
        GoldenRecord rec;
        if (fread(&rec, sizeof(rec), 1, f) != 1) {
            fprintf(stderr, "replay: truncated file at step %" PRIu64 "\n", step);
            fclose(f); free_env(env); return 1;
        }
        env->actions[0] = (float)rec.action;
        c_step(env);

        uint8_t actual[20];
        hash_step(env, actual);
        uint8_t actual_term = (env->terminals[0] != 0.0f) ? 1 : 0;
        float   actual_rew  = env->rewards[0];

        if (memcmp(actual, rec.hash, 20) != 0 ||
            actual_term != rec.terminal ||
            actual_rew  != rec.reward) {
            char e_hex[41], a_hex[41];
            hex20(rec.hash, e_hex);
            hex20(actual,   a_hex);
            fprintf(stderr, "MISMATCH at step %" PRIu64 ":\n", step);
            fprintf(stderr, "  action=%d (key=0x%02x)\n", rec.action,
                    NETHACK_ACTION_TABLE[rec.action]);
            fprintf(stderr, "  expected hash: %s  reward=%.6f terminal=%u\n",
                    e_hex, rec.reward, rec.terminal);
            fprintf(stderr, "  actual   hash: %s  reward=%.6f terminal=%u\n",
                    a_hex, actual_rew, actual_term);
            dump_chars(env);
            fclose(f); free_env(env); return 3;
        }
    }
    fclose(f);
    printf("replay: OK — %" PRIu64 " steps match\n", h.n_steps);

    if (a->bytewise) {
        bytewise_dump();
    }
    free_env(env);
    return 0;
}

int main(int argc, char** argv) {
    Args a;
    if (parse_args(argc, argv, &a) != 0 || !a.mode) {
        usage(argv[0] ? argv[0] : "verify_determinism");
        return 1;
    }
    if (!strcmp(a.mode, "record")) return do_record(&a);
    if (!strcmp(a.mode, "replay")) return do_replay(&a);
    usage(argv[0]);
    return 1;
}

// ---------------------------------------------------------------------------
// Sanity-test results (see exp_018_determinism/NOTES.md for the full log)
// ---------------------------------------------------------------------------
//   1. -Wall -Wextra compile: CLEAN (warnings inside nethack.h/profile.h are
//      suppressed via #pragma around the include; our own code is strict).
//   2. record --seed 42 --steps 1000 --action-seed 99 --out /tmp/g1.bin: OK,
//      "wrote 1000 steps to /tmp/g1.bin (obs_size=1767)".
//   3. replay --in /tmp/g1.bin: OK, "1000 steps match".
//   4. record same args -> /tmp/g2.bin; cmp /tmp/g1.bin /tmp/g2.bin:
//      IDENTICAL. The current env IS deterministic given a seeded
//      nle_seeds_init_t with reseed=0. No non-determinism findings.
//
// If a future run of step 4 ever FAILS, the most likely culprits are:
//   - NLE's anti-TAS reseed (we set reseed=0; if someone flips it, the
//     core RNG gets re-seeded mid-game from a process-local PRNG state).
//   - Direct time()/gettimeofday() in vendored NetHack source (e.g.
//     hacklib.c's `getnow`, `getlt`, or u_init's gettimeofday).
//   - ASLR-dependent ordering bugs in NetHack's many global structures
//     (pointers compared/stored, hash-set iteration order, etc.).
// ---------------------------------------------------------------------------
